import Head from "next/head";
import Arrivals from "../components/arrivals";
import Banner from "../components/banner";
import Categories from "../components/categories";
import Features from "../components/features";
import { Hero } from "../components/hero";
import Offers from "../components/offers";
import Recomended from "../components/recomended";

export default function Home() {
  return (
    <div>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Hero />
      <div className="container">
        <Features />
        <Offers />
        <Categories />
        <Arrivals />
        <Banner />
        <Recomended />
      </div>
    </div>
  );
}
